name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Specify the release version'
        required: true

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Change this to your desired .NET version

      - name: Build and Publish Projects
        run: |
          $projects = @("Mul-Ty-Player Client", "Mul-Ty-Player Server", "Mul-Ty-Player Updater")
          
          foreach ($project in $projects) {
          dotnet restore "$project/$project.csproj"
          dotnet build "$project/$project.csproj" --configuration Release
          dotnet publish "$project/$project.csproj" --configuration Release -o "publish/$project"
          }

      - name: Zip Published Projects
        run: |
          $projects = @("Mul-Ty-Player Client", "Mul-Ty-Player Server", "Mul-Ty-Player Updater")
          
          foreach ($project in $projects) {
            Compress-Archive -Path "publish/$project/*" -DestinationPath "publish/$project.zip"
          }

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: Release ${{ github.event.inputs.release_version }}
          latest: true
          draft: false
          prerelease: false

      - name: Upload Zipped Projects
        uses: actions/upload-artifact@v2
        with:
          name: projects
          path: ./publish/**/*.zip
